---
  - name: Install the {{ payload }} software for load-balancer
    package:
      name:
        - " {{ payload }}"
      state: latest
    register: result

  - name: Configure {{ payload }} configuration file 
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: start {{ payload }}

  - name: Enable and Start service {{ payload }}
    service:
      name: "{{ payload }}"
      state: started
      enabled: yes
